version: '3'

services:
    unblockneteasemusic:
        build: .
        environment:
            NODE_ENV: production

        # Change sources here
        # command: ["-o", "bilibili", "kugou", "kuwo", "ytdlp"]
        ports:
            - ${HTTP_PROXY_PORT:-58081}:58081
            - ${HTTPS_PROXY_PORT:-58082}:58082
